version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: slabiak/appointmentscheduler:0.0.1-SNAPSHOT
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/appointmentscheduler?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=thuphuong123
    restart: always
    depends_on:
      - appointmentscheduler_db
      - redis
    networks:
      - appointmentscheduler_network

  appointmentscheduler_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: appointmentscheduler
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - appointmentscheduler_volume:/var/lib/mysql
      - ./src/main/resources:/docker-entrypoint-initdb.d
    networks:
      - appointmentscheduler_network

  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - REDIS_PASSWORD=thuphuong123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - appointmentscheduler_network

volumes:
  appointmentscheduler_volume:
  redis_data:

networks:
  appointmentscheduler_network:
